version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: contacts_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app: 
    build: ./backend
    container_name: contacts_backend
    environment:
      DATABASE_URL: ${DATABASE_URL} 
    depends_on:
      db:
        condition: service_healthy

  frontend: 
    build: ./frontend
    container_name: contacts_frontend
    ports:
      - "80:80" 
    depends_on:
      - app 

volumes:
  db_data:
